# .github/dependabot.yml

version: 2

updates:
  # =========================
  # Yarn Dependencies
  # =========================
  - package-ecosystem: "yarn"
    directory: "/"              # or "/client" if package.json is inside a subfolder
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 10

    groups:
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"

    allow:
      - dependency-type: "all"

    labels:
      - "dependencies"
      - "yarn"

    commit-message:
      prefix: "chore"
      include: "scope"

  # =========================
  # GitHub Actions
  # =========================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Kolkata"

    labels:
      - "dependencies"
      - "github-actions"

    commit-message:
      prefix: "ci"

    groups:
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"